<?php

$labels = array(
  'name'                  => _x( 'Mobile Stories', 'Post Type General Name', 'text_domain' ),
  'singular_name'         => _x( 'Mobile Story', 'Post Type Singular Name', 'text_domain' ),
  'menu_name'             => __( 'Mobile Stories', 'text_domain' ),
  'name_admin_bar'        => __( 'Mobile Story', 'text_domain' ),
  'archives'              => __( 'Mobile Story Archives', 'text_domain' ),
  'attributes'            => __( 'Mobile Story Attributes', 'text_domain' ),
  'parent_item_colon'     => __( 'Parent Mobile Story:', 'text_domain' ),
  'all_items'             => __( 'All Mobile Stories', 'text_domain' ),
  'add_new_item'          => __( 'Add New Mobile Story', 'text_domain' ),
  'add_new'               => __( 'Add New', 'text_domain' ),
  'new_item'              => __( 'New Mobile Story', 'text_domain' ),
  'edit_item'             => __( 'Edit Mobile Story', 'text_domain' ),
  'update_item'           => __( 'Update Mobile Story', 'text_domain' ),
  'view_item'             => __( 'View Mobile Story', 'text_domain' ),
  'view_items'            => __( 'View Mobile Stories', 'text_domain' ),
  'search_items'          => __( 'Search Mobile Stories', 'text_domain' ),
  'not_found'             => __( 'Not found', 'text_domain' ),
  'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
  'featured_image'        => __( 'Featured Image', 'text_domain' ),
  'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
  'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
  'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
  'insert_into_item'      => __( 'Insert into item', 'text_domain' ),
  'uploaded_to_this_item' => __( 'Uploaded to this item', 'text_domain' ),
  'items_list'            => __( 'Items list', 'text_domain' ),
  'items_list_navigation' => __( 'Items list navigation', 'text_domain' ),
  'filter_items_list'     => __( 'Filter items list', 'text_domain' ),
);
$args = array(
  'label'                 => __( 'Mobile Story', 'text_domain' ),
  'description'           => __( 'Create stories for moile-first readers', 'text_domain' ),
  'labels'                => $labels,
  'supports'              => array( 'title', 'editor', 'thumbnail', 'revisions' ),
  'taxonomies'            => array( 'category', 'post_tag' ),
  'hierarchical'          => false,
  'public'                => true,
  'show_ui'               => true,
  'show_in_menu'          => true,
  'menu_position'         => 5,
  'show_in_admin_bar'     => true,
  'show_in_nav_menus'     => true,
  'can_export'            => true,
  'has_archive'           => true,
  'exclude_from_search'   => false,
  'publicly_queryable'    => true,
  'capability_type'       => 'page',
  'menu_icon'             => 'dashicons-images-alt2',
  'show_in_rest'          => true,
);
register_post_type( 'mobile_stories', $args );

